services:
  - type: web
    name: keysshop
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: postgresql://keysshopdb_user:TXFgDCd1SnDxmEOnjTrR6RZCXSLzjkzq@dpg-d5chq9ili9vc73cibbdg-a.frankfurt-postgres.render.com/keysshopdb
    plan: free